import os

os.system('cls')

print('Solicitando dados - ')

valor_a = float(input('Digite o valor A'))
valor_b = float(input('Digite o valor B'))
valor_c = float(input('Digite o valor C'))

#Cálculo de soma
soma = a + b 
print ('A soma de A + B',  {soma})

#Comparação 

if soma < C:
    print = ('A + B é maior que C')
elif soma > C:
        print('A + B é maior que C')
else:
      print('A + B é igual a C')